jdk: oraclejdk8

language: java

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - "$HOME/.m2"
    - "$HOME/.gradle"
    - "$HOME/.gradle/caches/"
    - "$HOME/.gradle/wrapper/"

script:
  - "./gradlew clean build --stacktrace"

deploy:
  provider: releases
  api_key:
    secure: nsfbbmO64VkuSgcD5B/X21eN/99Kv0cg/CdRdqHcko+7QEB8UZJqft5h3D8jntRxi3bgcJ0j1+6NS7fs5LPhNoEn9nnBhFLI89/ZspP7pw9zbZ/iqLTYHN//wwKq2w76MBp5XIOrIDLMDKzyKnCfbkQITH0sdT5FYSjX63W6cMQ=
  file: plugin-digitalocean-server/build/distributions/digitalocean-cloud.zip
  skip_cleanup: true
  on:
    tags: true
    repo: graf/digitalocean-teamcity-plugin
